version: '3.3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'store_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: