spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_db
    username: user
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  liquibase:
    change-log: master-changelog.yaml
#logging:
#  level:
#    root: warn
#    org:
#      springframework:
#        security: debug


#server:
#  servlet:
#    session:
#      timeout: 10
